include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false




    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: false
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: false
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false
  
    # Back to the 80s
    lines_longer_than_80_chars: false

    avoid_function_literals_in_foreach_calls: false

    avoid_print: false

    avoid_void_async: false

    prefer_const_constructors_in_immutables: false

    prefer_equal_for_default_values: false

    directives_ordering: false